#!/usr/bin/env python3
"""Universal notification/content receiver.

This service accepts POSTed content, annotates receive time, and appends one JSON
object per line to a file so downstream programs can consume the records later.
When the payload is a WhatsApp notification containing a GoPay verification code,
it also mirrors the OTP into WebUI's SQLite-backed `wa_state` so the GoPay
pipeline can consume it through the existing `/api/whatsapp/latest-otp` relay.

Authentication is mandatory. On startup the service reads NOTIFY_RELAY_KEY from
key.env; if the file/key is missing, it creates a new random key and writes it to
key.env with 0600 permissions.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import secrets
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

_WRITE_LOCK = threading.Lock()
_ARGS: argparse.Namespace
_RELAY_KEY = ""
_LATEST: dict[str, Any] | None = None
_COUNT = 0
_OTP_KEYWORDS = (
    "otp",
    "one-time",
    "one time",
    "verification",
    "verify",
    "code",
    "kode",
    "verifikasi",
    "gopay",
    "gojek",
    "验证码",
    "驗證碼",
)


def utc_now() -> tuple[float, str]:
    ts = time.time()
    iso = _dt.datetime.fromtimestamp(ts, tz=_dt.timezone.utc).isoformat().replace("+00:00", "Z")
    return ts, iso


def json_response(handler: BaseHTTPRequestHandler, status: int, obj: dict[str, Any]) -> None:
    raw = json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(raw)))
    handler.end_headers()
    handler.wfile.write(raw)


def parse_key_env(text: str) -> str:
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if k.strip() == "NOTIFY_RELAY_KEY":
            val = v.strip().strip('"').strip("'")
            if val:
                return val
    return ""


def write_key_env(path: Path, key: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    ts = _dt.datetime.now(tz=_dt.timezone.utc).isoformat().replace("+00:00", "Z")
    content = (
        "# Auto-generated by notify_receiver.py\n"
        f"# generated_at={ts}\n"
        "# Put this value into the Android App 接收密钥 field. Do not share it.\n"
        f"NOTIFY_RELAY_KEY={key}\n"
    )
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
        f.flush()
        os.fsync(f.fileno())
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def load_or_create_key(path: Path) -> str:
    if path.exists():
        key = parse_key_env(path.read_text(encoding="utf-8", errors="replace"))
        if key:
            try:
                os.chmod(path, 0o600)
            except OSError:
                pass
            return key
    key = secrets.token_urlsafe(32)
    write_key_env(path, key)
    return key


def read_body(handler: BaseHTTPRequestHandler) -> bytes:
    try:
        length = int(handler.headers.get("Content-Length", "0") or "0")
    except ValueError:
        length = 0
    if length > _ARGS.max_body_bytes:
        raise ValueError(f"body too large: {length} > {_ARGS.max_body_bytes}")
    return handler.rfile.read(length) if length > 0 else b""


def parse_payload(raw: bytes, content_type: str) -> Any:
    if not raw:
        return {}
    text = raw.decode("utf-8", errors="replace")
    ctype = (content_type or "").split(";", 1)[0].strip().lower()
    if ctype == "application/json" or text.lstrip().startswith(("{", "[")):
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return {"raw_text": text, "parse_error": "invalid_json"}
    if ctype == "application/x-www-form-urlencoded":
        parsed = urllib.parse.parse_qs(text, keep_blank_values=True)
        return {k: v[0] if len(v) == 1 else v for k, v in parsed.items()}
    return {"raw_text": text}


def first_str(obj: Any, keys: tuple[str, ...]) -> str:
    if isinstance(obj, dict):
        for key in keys:
            val = obj.get(key)
            if isinstance(val, str) and val.strip():
                return val
    return ""


def append_text(parts: list[str], value: Any) -> None:
    if value is None:
        return
    if isinstance(value, str):
        s = value.strip()
        if s:
            parts.append(s)
        return
    if isinstance(value, (list, tuple)):
        for item in value:
            append_text(parts, item)
        return
    if isinstance(value, dict):
        for key in (
            "title", "text", "body", "message", "content", "big_text", "bigText",
            "sub_text", "subText", "summary_text", "summaryText", "text_lines", "textLines", "lines",
        ):
            if key in value:
                append_text(parts, value.get(key))


def combined_content(payload: Any) -> str:
    parts: list[str] = []
    append_text(parts, payload)
    seen: set[str] = set()
    out: list[str] = []
    for part in parts:
        if part not in seen:
            seen.add(part)
            out.append(part)
    content = "\n".join(out).strip()
    if len(content) > _ARGS.max_content_chars:
        content = content[: _ARGS.max_content_chars] + "\n..."
    return content


def _nested_get(obj: Any, path: tuple[str, ...]) -> Any:
    cur = obj
    for key in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
    return cur


def _payload_timestamp(payload: Any) -> float:
    if not isinstance(payload, dict):
        return 0.0
    for key in ("ts", "post_time", "timestamp", "received_ts"):
        value = payload.get(key)
        if value not in (None, ""):
            try:
                ts = float(value)
                if ts > 1_000_000_000_000:
                    ts /= 1000.0
                return ts
            except (TypeError, ValueError):
                pass
    return 0.0


def extract_gopay_otp(text: str) -> str:
    if not text:
        return ""
    patterns = [
        r"(?:otp|one[-\s]*time|verification|verify|code|kode|verifikasi|gopay|gojek|验证码|驗證碼)[^\d]{0,100}(\d{4,8})(?!\d)",
        r"(?<!\d)(\d{4,8})(?!\d)[^\n\r]{0,100}(?:otp|one[-\s]*time|verification|verify|code|kode|verifikasi|gopay|gojek|验证码|驗證碼)",
        r"(?<!\d)(\d{6})(?!\d)",
    ]
    for pattern in patterns:
        for match in reversed(list(re.finditer(pattern, text, flags=re.IGNORECASE | re.DOTALL))):
            groups = match.groups() or (match.group(0),)
            for group in reversed(groups):
                digits = re.sub(r"\D", "", str(group or ""))
                if 4 <= len(digits) <= 8:
                    return digits
    return ""


def should_sync_gopay_otp(record: dict[str, Any]) -> bool:
    payload = record.get("payload")
    package = ""
    title = ""
    if isinstance(payload, dict):
        package = str(payload.get("package") or payload.get("from") or "")
        title = str(_nested_get(payload, ("notification", "title")) or "")
    content = str(record.get("content") or "")
    haystack = f"{title}\n{content}".lower()
    if package and package != "com.whatsapp":
        return False
    if package != "com.whatsapp" and "whatsapp" not in haystack:
        return False
    return "gopay" in haystack and any(k in haystack for k in _OTP_KEYWORDS)


def sync_webui_gopay_otp(record: dict[str, Any]) -> str:
    """Mirror a GoPay OTP notification into WebUI's SQLite wa_state.

    Returns the mirrored OTP, or an empty string when the record is not a GoPay
    WhatsApp OTP notification. Errors are swallowed so notification capture keeps
    working even if WebUI's database is temporarily unavailable.
    """
    if getattr(_ARGS, "no_webui_otp_sync", False):
        return ""
    if not should_sync_gopay_otp(record):
        return ""
    code = extract_gopay_otp(str(record.get("content") or ""))
    if not code:
        return ""
    try:
        from webui.backend.db import get_db
    except Exception:
        return ""

    payload = record.get("payload") if isinstance(record.get("payload"), dict) else {}
    ts = _payload_timestamp(payload) or float(record.get("received_ts") or time.time())
    notification_key = str(payload.get("notification_key") or "")
    item = {
        "otp": code,
        "ts": ts,
        "received_ts": float(record.get("received_ts") or time.time()),
        "from": str(payload.get("package") or payload.get("from") or "com.whatsapp"),
        "source": "android_notification",
        "engine": "notify_receiver",
        "id": notification_key,
        "text": str(record.get("content") or "")[:500],
    }
    try:
        db = get_db()
        state_key = getattr(_ARGS, "webui_otp_state_key", "wa_state")
        state = db.get_runtime_json(state_key, {})
        if not isinstance(state, dict):
            state = {}
        history = state.get("history") if isinstance(state.get("history"), list) else []
        if not any(isinstance(old, dict) and old.get("id") == notification_key and old.get("otp") == code for old in history[-10:]):
            history.append(item)
        state.update({
            "status": state.get("status") or "notification_received",
            "latest": item,
            "history": history[-50:],
            "updated_at": time.time(),
        })
        db.set_runtime_json(state_key, state)
        return code
    except Exception:
        return ""


def check_key(handler: BaseHTTPRequestHandler) -> bool:
    got = handler.headers.get("X-Relay-Key", "").strip()
    if not got:
        got = handler.headers.get("X-Relay-Token", "").strip()  # backward-compatible header name
    auth = handler.headers.get("Authorization", "").strip()
    if auth.lower().startswith("bearer "):
        auth = auth[7:].strip()
    return bool(_RELAY_KEY) and (secrets.compare_digest(got, _RELAY_KEY) or secrets.compare_digest(auth, _RELAY_KEY))


def append_record(record: dict[str, Any]) -> int:
    global _LATEST, _COUNT
    output = Path(_ARGS.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(record, ensure_ascii=False, separators=(",", ":")) + "\n"
    with _WRITE_LOCK:
        with output.open("a", encoding="utf-8") as f:
            f.write(line)
            f.flush()
            if _ARGS.fsync:
                os.fsync(f.fileno())
        _LATEST = record
        _COUNT += 1
        return _COUNT


class NotifyReceiver(BaseHTTPRequestHandler):
    server_version = "NotifyReceiver/1.1"

    def do_GET(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path in ("/health", "/"):
            json_response(self, 200, {
                "ok": True,
                "service": "notify_receiver",
                "auth_required": True,
                "key_file": str(Path(_ARGS.key_file)),
                "records_in_process": _COUNT,
                "output": str(Path(_ARGS.output)),
            })
            return
        if parsed.path == "/latest":
            if not check_key(self):
                json_response(self, 401, {"ok": False, "error": "unauthorized"})
                return
            json_response(self, 200, {"ok": True, "latest": _LATEST})
            return
        json_response(self, 404, {"ok": False, "error": "not_found"})

    def do_POST(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path not in ("/", "/ingest", "/notify", "/webhook"):
            json_response(self, 404, {"ok": False, "error": "not_found"})
            return
        if not check_key(self):
            json_response(self, 401, {"ok": False, "error": "unauthorized"})
            return
        try:
            raw = read_body(self)
            payload = parse_payload(raw, self.headers.get("Content-Type", ""))
        except Exception as exc:
            json_response(self, 400, {"ok": False, "error": str(exc)})
            return

        qs = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
        ts, iso = utc_now()
        remark = ""
        if "remark" in qs and qs["remark"]:
            remark = qs["remark"][0]
        if not remark:
            remark = first_str(payload, ("remark", "note", "memo", "comment"))

        record = {
            "received_at": iso,
            "received_ts": ts,
            "path": parsed.path,
            "remark": remark,
            "client": {
                "ip": self.client_address[0] if self.client_address else "",
                "user_agent": self.headers.get("User-Agent", ""),
            },
            "content_type": self.headers.get("Content-Type", ""),
            "source": first_str(payload, ("source", "app", "from", "package")),
            "content": combined_content(payload),
            "payload": payload,
        }
        count = append_record(record)
        synced_otp = sync_webui_gopay_otp(record)
        json_response(self, 200, {
            "ok": True,
            "stored": 1,
            "count_in_process": count,
            "received_at": iso,
            "webui_otp_synced": bool(synced_otp),
        })

    def log_message(self, fmt: str, *args: Any) -> None:
        if _ARGS.quiet:
            return
        ts = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"[{ts}] {self.address_string()} {fmt % args}", flush=True)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generic authenticated POST receiver that appends received content to JSONL.")
    p.add_argument("--host", default="0.0.0.0")
    p.add_argument("--port", type=int, default=8788)
    p.add_argument("--output", default="data/notifications.jsonl")
    p.add_argument("--key-file", default="key.env", help="env file containing NOTIFY_RELAY_KEY; auto-created if missing")
    p.add_argument("--max-body-bytes", type=int, default=1024 * 1024)
    p.add_argument("--max-content-chars", type=int, default=20000)
    p.add_argument("--fsync", action="store_true", help="fsync after every write")
    p.add_argument("--no-webui-otp-sync", action="store_true", help="do not mirror GoPay WhatsApp OTP notifications into WebUI SQLite")
    p.add_argument("--webui-otp-state-key", default="wa_state", help="runtime_meta key used by WebUI's WhatsApp OTP relay")
    p.add_argument("--quiet", action="store_true")
    return p.parse_args()


def main() -> None:
    global _ARGS, _RELAY_KEY
    _ARGS = parse_args()
    Path(_ARGS.output).parent.mkdir(parents=True, exist_ok=True)
    key_path = Path(_ARGS.key_file)
    _RELAY_KEY = load_or_create_key(key_path)
    srv = ThreadingHTTPServer((_ARGS.host, _ARGS.port), NotifyReceiver)
    print(f"Notify receiver listening on http://{_ARGS.host}:{_ARGS.port}", flush=True)
    print(f"Writing JSONL records to {Path(_ARGS.output).resolve()}", flush=True)
    print(f"Authentication key file: {key_path.resolve()} (value not printed)", flush=True)
    srv.serve_forever()


if __name__ == "__main__":
    main()
